#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: us
  
  identity:
    username: sccm
    password: $6$w/pNVVwrym7r5iMe$/S/StGWGAHfh/cWSCw1q4rNskFfof9npZlPIXSrKG0Awb3ppCyVtKcKrA9Vli8hDJEAbho9NDSHqPiEE7krTt0 

  ssh:
    install-server: true
    allow-pw: true

  packages:
    - dpkg
    - curl
    - gpg
    - openssh-server
    - python3

  late-commands:
    - echo 'sccm ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/sccm